# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
orbs: 
  cypress: cypress-io/cypress@3

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build:
    jobs:
      - cypress/run: # "run" job comes from "cypress" orb
          parallelism: 2
          install-browsers: true
          cypress-command: 'npx cypress run --browser chrome --parallel --record --group all tests --ci-build-id circle --key 3f12b95e-b5c7-4692-b966-a40d73344341'